controllers/CompetitionController.php
<?php

namespace app\controllers;

use app\models\Competition;
use app\models\CompetitionTeam;
use app\models\Team;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\web\Response;

class CompetitionController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'delete', 'team', 'team-delete' ,'available-team'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }


    /**
     * Displays competition.
     *
     * @param null $id
     * @return string
     */
    public function actionIndex($id = null)
    {
        if (!$id) {
            $model = new Competition;
        } else {
            $model = Competition::findOne($id);
        }

        if ($model && $model->load(Yii::$app->request->post()) && $model->create()) {
            Yii::$app->session->setFlash('success', 'Success.');
            $model = new Competition;
        }

        $provider = new ActiveDataProvider([
            'query' => Competition::find(),
        ]);
        return $this->render('index', [
            'model' => $model,
            'dataProvider' => $provider,
        ]);
    }


    /**
     * @param null $id
     * @return string
     */
    public function actionTeam($id = null)
    {
        if (!$id) {
            $model = new CompetitionTeam;
        } else {
            $model = CompetitionTeam::findOne($id);
        }

        if ($model && $model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Success.');
            $model = new CompetitionTeam;
        }

        $dataProvider = new ActiveDataProvider([
            'query' => Competition::find(),
        ]);

        return $this->render('team', [
            'model' => $model,
            'dataProvider' => $dataProvider,
            'competitions' => Competition::find()->andWhere(['>', 'date_from', Yii::$app->formatter->asTimestamp('now')])->all()
        ]);
    }

    /**
     * @return array
     */
    public function actionAvailableTeam()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        if (Yii::$app->request->post()) {
            /** @var int $id Shop.id */
            $id = Yii::$app->request->getBodyParam('depdrop_parents');
            if (is_array($id)) {
                $id = $id[0];
            }
            $ids = ArrayHelper::getColumn(CompetitionTeam::findAll(['competition_id' => $id]),'team_id');
            $teams = Team::find()->andWhere(['not in', 'id', $ids])->all();
            return ['output' => $teams, 'selected' => ''];
        }
        return ['output' => '', 'selected' => ''];
    }


    /**
     * Delete competition.
     *
     * @return string
     */
    public function actionDelete($id)
    {
        $model = Competition::findOne($id);

        if ($model->competitionMatches) {
            Yii::$app->session->setFlash('danger', 'Cant remove competition. It has matches.');
        } elseif ($model->delete()) {
            Yii::$app->session->setFlash('success', 'Success.');
        }

        $provider = new ActiveDataProvider([
            'query' => Competition::find(),
        ]);

        return $this->render('index', [
            'model' => new Competition,
            'dataProvider' => $provider,
        ]);
    }

    /**
     * Displays competition.
     *
     * @return string
     */
    public function actionTeamDelete($id)
    {
        $model = CompetitionTeam::findOne($id);

        if ($model) {
            if ($model->hasMatch()) {
                Yii::$app->session->setFlash('danger', 'Cant remove competition. It has matches.');
            } elseif ($model->delete()) {
                Yii::$app->session->setFlash('success', 'Success.');
            }
        }

        return $this->redirect(['team']);
    }


}

controllers/CompetitionMatchesController.php
<?php

namespace app\controllers;

use app\models\Competition;
use app\models\CompetitionMatch;
use app\models\CompetitionTeam;
use app\models\MatchResultForm;
use app\models\Player;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\web\Response;

class CompetitionMatchesController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'available-players', 'available-teams', 'update'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @param null $id
     * @return string
     */
    public function actionIndex($id = null)
    {
        if (!$id) {
            $model = new CompetitionMatch;
        } else {
            $model = CompetitionMatch::findOne($id);
        }

        if ($model && $model->load(Yii::$app->request->post()) && $model->saveMatch()) {
            Yii::$app->session->setFlash('success', 'Success.');
            $model = new CompetitionMatch();
        }

        $dataProvider = new ActiveDataProvider([
            'query' => CompetitionMatch::find(),
        ]);

        return $this->render('index', [
            'model' => $model,
            'dataProvider' => $dataProvider,
            'teams' => CompetitionTeam::find()->all(),
            'competitions' => Competition::find()->all(),
        ]);
    }


    /**
     * @return array
     */
    public function actionAvailablePlayers()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        if (Yii::$app->request->post()) {
            /** @var int $id Shop.id */
            $id = Yii::$app->request->getBodyParam('depdrop_parents');
            if (is_array($id)) {
                $id = $id[0];
            }
            $output = Player::forDepDrop($id);
            return ['output' => $output, 'selected' => ''];
        }
        return ['output' => '', 'selected' => ''];
    }


    /**
     * @return array
     */
    public function actionAvailableTeams()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        if (Yii::$app->request->post()) {
            /** @var int $id Shop.id */
            $id = Yii::$app->request->getBodyParam('depdrop_parents');
            if (is_array($id)) {
                $id = $id[0];
            }
            $out = CompetitionTeam::teamsForDepDrop($id);
            return ['output' => $out, 'selected' => ''];
        }
        return ['output' => '', 'selected' => ''];
    }

    /**
     * @param $id
     * @return string|Response
     */
    public function actionUpdate($id)
    {
        $match = CompetitionMatch::findOne($id);
        if ($match) {
            $model = new MatchResultForm(['match' => $match]);
            if ($model->load(Yii::$app->request->post()) && $model->saveResult()) {
                Yii::$app->session->setFlash('success', 'Success.');
            }
            return $this->render('result', ['match' => $match, 'model' => $model]);
        }

       return $this->redirect(['index']);
    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\SignupForm;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }

    /**
     * Register User
     * @return string|Response
     */
    public function actionRegister()
    {
        $model = new SignupForm;

        if ($model->load(Yii::$app->request->post()) && $model->signup()) {
            Yii::$app->session->setFlash('success', 'Register success. You can now login.');
            return $this->redirect(['site/index']);
        }

        return $this->render('register', ['model' => $model]);
    }
}

controllers/TeamController.php
<?php

namespace app\controllers;

use app\models\Competition;
use app\models\Player;
use app\models\Team;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\web\Response;

class TeamController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'delete', 'squads'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }


    /**
     * Displays competition.
     *
     * @param null $id
     * @return string
     */
    public function actionIndex($id = null)
    {
        if (!$id) {
            $model = new Team;
        } else {
            $model = Team::findOne($id);
        }

        if ($model && $model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Success.');
            $model = new Team;
        }

        $provider = new ActiveDataProvider([
            'query' => Team::find(),
        ]);
        return $this->render('index', [
            'model' => $model,
            'dataProvider' => $provider,
        ]);
    }

    /**
     * Squads competition.
     *
     * @param null $id
     * @return string
     */
    public function actionSquads($id = null)
    {
        if (!$id) {
            $model = new Player;
        } else {
            $model = Player::findOne($id);
        }

        if ($model && $model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Success.');
            $model = new Player;
        }

        $provider = new ActiveDataProvider([
            'query' => Team::find(),
        ]);
        return $this->render('squad', [
            'model' => $model,
            'dataProvider' => $provider,
        ]);
    }


    /**
     * Displays competition.
     *
     * @param $id
     * @return string
     */
    public function actionDelete($id)
    {
        $model = Team::findOne($id);

        if ($model && $model->competitionTeams) {
            Yii::$app->session->setFlash('danger', 'Cant remove competition. It has matches.');
        } else
        if ($model && $model->delete()) {
            Yii::$app->session->setFlash('success', 'Success.');
        }

        $provider = new ActiveDataProvider([
            'query' => Team::find(),
        ]);

        return $this->render('index', [
            'model' => new Team,
            'dataProvider' => $provider,
        ]);
    }


}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\assets\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Competition Schelude',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);

    $items [] = ['label' => 'Home', 'url' => ['/site/index']];

    if (Yii::$app->user->isGuest) {
        $items[] = ['label' => 'Login', 'url' => ['/site/login']];
        $items[] = ['label' => 'Register', 'url' => ['/site/register']];
    } else {
        $items[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->fullName . ')',
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>';
    }

    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $items
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget()?>
        <?php if (!Yii::$app->user->isGuest) : ?>
        <div class="col-md-3">
            <?= $this->render('side-menu')?>
        </div>
        <div class="col-md-9">
            <?= $content ?>
        </div>
        <?php else: ?>
        <div class="col-md-12">
            <?= $content ?>
        </div>
        <?php endif; ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Competition <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/side-menu.php
<?php

use kartik\sidenav\SideNav;
use yii\helpers\Url;

/** @var \yii\web\View $this */

$type = SideNav::TYPE_INFO;
$item = Yii::$app->request->url;
?>

<?=
SideNav::widget([
    'type' => $type,
    'encodeLabels' => false,
    'items' => [
        ['label' => 'Home', 'url' => Url::to(['/site/index']), 'active' => ($item == '/site/index')],
        ['label' => 'Competitions', 'url' => Url::to(['/competition/index']), 'active' => ($item == 'competition/index')],
        ['label' => 'Teams', 'url' => Url::to(['/team/index']), 'active' => ($item == '/team/index')],
        ['label' => 'Teams Squads', 'url' => Url::to(['/team/squads']), 'active' => ($item == '/team/squads')],
        ['label' => 'Competitions Teams', 'url' => Url::to(['/competition/team']), 'active' => ($item == 'competition/team')],
        ['label' => 'Competitions Matches', 'url' => Url::to(['/competition-matches/index']), 'active' => ($item == 'competition-matches/index')],
    ]
]);
?>