models/Competition.php
<?php

namespace app\models;

use Yii;
use yii\helpers\Html;

/**
 * This is the model class for table "{{%competition}}".
 *
 * @property integer $id
 * @property string $name
 * @property integer $date_from
 * @property integer $date_to
 *
 * @property CompetitionTeam[] $competitionTeams
 * @property CompetitionMatch[] $competitionMatches
 * @property CompetitionTable[] $competitionTables
 */
class Competition extends \yii\db\ActiveRecord
{

    public $dateTimeStart;
    public $dateTimeEnd;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%competition}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['name', 'unique'],
            [['name', 'dateTimeStart', 'dateTimeEnd'], 'required'],
            [['dateTimeStart', 'dateTimeEnd'], function ($attribute, $params, $validator) {
                if (!empty($this->dateTimeStart) && !empty($this->dateTimeEnd) && (Yii::$app->formatter->asTimestamp($this->dateTimeStart) > Yii::$app->formatter->asTimestamp($this->dateTimeEnd))) {
                    $this->addError($attribute, 'Date end cannot be lesser than date start.');
                }
            }],
            [['date_from', 'date_to'], 'integer'],
            [['name'], 'string', 'max' => 150],
        ];
    }

    public function afterFind()
    {
        parent::afterFind();
        $this->dateTimeEnd = Yii::$app->formatter->asDatetime($this->date_to, 'php:yy-m-d G:i');
        $this->dateTimeStart = Yii::$app->formatter->asDatetime($this->date_from, 'php:yy-m-d G:i');
    }

    /**
     * @inheritdoc
     */
    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            $this->date_from = (int)Yii::$app->formatter->asTimestamp($this->dateTimeStart);
            $this->date_to = (int)Yii::$app->formatter->asTimestamp($this->dateTimeEnd);
            return true;
        }
        return false;
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'date_from' => Yii::t('app', 'Date From'),
            'date_to' => Yii::t('app', 'Date To'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompetitionTeams()
    {
        return $this->hasMany(CompetitionTeam::className(), ['competition_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompetitionMatches()
    {
        return $this->hasMany(CompetitionMatch::className(), ['competition_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompetitionTables()
    {
        return $this->hasMany(CompetitionTable::className(), ['competition_id' => 'id']);
    }

    public function create()
    {
        if (!$this->validate()) {
            return false;
        }
        return $this->save();
    }

    public function teamHtml()
    {
        $html = '';
        foreach ($this->competitionTeams as $competitionTeam) {
            $field = !$competitionTeam->hasMatch() ? Html::a('<span class="glyphicon glyphicon-remove"></span>',
                ['competition/team-delete', 'id' => $competitionTeam->id], [
                    'class' => 'button-delete-attribute',
                    'title' => Yii::t('app', 'Delete'),
                ]) : '';
            $html .= Html::tag('li', $competitionTeam->team->name . ' ' . $field);
        }

        return Html::tag('ul', $html);
    }

}

models/CompetitionTable.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%competition_table}}".
 *
 * @property integer $id
 * @property integer $competition_id
 * @property integer $competition_team_id
 * @property integer $win
 * @property integer $lose
 *
 * @property Competition $competition
 * @property CompetitionTeam $competitionTeam
 */
class CompetitionTable extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%competition_table}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['competition_id', 'competition_team_id'], 'required'],
            [['competition_id', 'competition_team_id', 'win', 'lose'], 'integer'],
            [['competition_id'], 'exist', 'skipOnError' => true, 'targetClass' => Competition::className(), 'targetAttribute' => ['competition_id' => 'id']],
            [['competition_team_id'], 'exist', 'skipOnError' => true, 'targetClass' => CompetitionTeam::className(), 'targetAttribute' => ['competition_team_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'competition_id' => Yii::t('app', 'Competition ID'),
            'competition_team_id' => Yii::t('app', 'Competition Team ID'),
            'win' => Yii::t('app', 'Win'),
            'lose' => Yii::t('app', 'Lose'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompetition()
    {
        return $this->hasOne(Competition::className(), ['id' => 'competition_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompetitionTeam()
    {
        return $this->hasOne(CompetitionTeam::className(), ['id' => 'competition_team_id']);
    }
}

controllers/CompetitionController.php
<?php

namespace app\controllers;

use app\models\Competition;
use app\models\CompetitionTeam;
use app\models\Team;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\web\Response;

class CompetitionController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'delete', 'team', 'team-delete' ,'available-team'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }


    /**
     * Displays competition.
     *
     * @param null $id
     * @return string
     */
    public function actionIndex($id = null)
    {
        if (!$id) {
            $model = new Competition;
        } else {
            $model = Competition::findOne($id);
        }

        if ($model && $model->load(Yii::$app->request->post()) && $model->create()) {
            Yii::$app->session->setFlash('success', 'Success.');
            $model = new Competition;
        }

        $provider = new ActiveDataProvider([
            'query' => Competition::find(),
        ]);
        return $this->render('index', [
            'model' => $model,
            'dataProvider' => $provider,
        ]);
    }


    /**
     * @param null $id
     * @return string
     */
    public function actionTeam($id = null)
    {
        if (!$id) {
            $model = new CompetitionTeam;
        } else {
            $model = CompetitionTeam::findOne($id);
        }

        if ($model && $model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Success.');
            $model = new CompetitionTeam;
        }

        $dataProvider = new ActiveDataProvider([
            'query' => Competition::find(),
        ]);

        return $this->render('team', [
            'model' => $model,
            'dataProvider' => $dataProvider,
            'competitions' => Competition::find()->andWhere(['>', 'date_from', Yii::$app->formatter->asTimestamp('now')])->all()
        ]);
    }

    /**
     * @return array
     */
    public function actionAvailableTeam()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        if (Yii::$app->request->post()) {
            /** @var int $id Shop.id */
            $id = Yii::$app->request->getBodyParam('depdrop_parents');
            if (is_array($id)) {
                $id = $id[0];
            }
            $ids = ArrayHelper::getColumn(CompetitionTeam::findAll(['competition_id' => $id]),'team_id');
            $teams = Team::find()->andWhere(['not in', 'id', $ids])->all();
            return ['output' => $teams, 'selected' => ''];
        }
        return ['output' => '', 'selected' => ''];
    }


    /**
     * Delete competition.
     *
     * @return string
     */
    public function actionDelete($id)
    {
        $model = Competition::findOne($id);

        if ($model->competitionMatches) {
            Yii::$app->session->setFlash('danger', 'Cant remove competition. It has matches.');
        } elseif ($model->delete()) {
            Yii::$app->session->setFlash('success', 'Success.');
        }

        $provider = new ActiveDataProvider([
            'query' => Competition::find(),
        ]);

        return $this->render('index', [
            'model' => new Competition,
            'dataProvider' => $provider,
        ]);
    }

    /**
     * Displays competition.
     *
     * @return string
     */
    public function actionTeamDelete($id)
    {
        $model = CompetitionTeam::findOne($id);

        if ($model) {
            if ($model->hasMatch()) {
                Yii::$app->session->setFlash('danger', 'Cant remove competition. It has matches.');
            } elseif ($model->delete()) {
                Yii::$app->session->setFlash('success', 'Success.');
            }
        }

        return $this->redirect(['team']);
    }


}

views/competition/partials/create.php
<?php

use kartik\datetime\DateTimePicker;
use yii\bootstrap\Html;
use yii\widgets\ActiveForm;


?>

<?php
$form = ActiveForm::begin([
    'id' => 'create-form',
]); ?>

<?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>
<?= $form->field($model, 'dateTimeStart')->hint('Format RRRR-MM-DD GG:MM')->widget(DateTimePicker::classname(), [
    'type' => DateTimePicker::TYPE_INPUT,
    'pluginOptions' => [
        'format' => 'yyyy-mm-dd hh:ii']
]) ?>
<?= $form->field($model, 'dateTimeEnd')->hint('Format RRRR-MM-DD GG:MM')->widget(DateTimePicker::classname(), [
    'type' => DateTimePicker::TYPE_INPUT,
    'pluginOptions' => [
        'format' => 'yyyy-mm-dd hh:ii']
]) ?>

<div class="col-md-12">
    <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => 'btn btn-primary', 'style' => ['width' => '100%'], 'name' => 'create-button']) ?>
</div>

<?php ActiveForm::end(); ?>

views/competition/partials/search.php
<?php

use yii\grid\GridView;
use yii\helpers\Html;
?>

<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        'name',
        'date_from:date',
        'date_to:date',
        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{update} {delete}',
            'buttons' => [
                'update' => function ($url, $model) {
                    return Yii::$app->user->identity->isAdmin() && (int) Yii::$app->formatter->asTimestamp('now') > $model->date_from
                        ? Html::a('<span class="glyphicon glyphicon-pencil"> </span>',
                            ['competition/index', 'id' => $model->id], [
                                'class' => 'button-attribute-update',
                                'title' => Yii::t('app', 'Update'),
                            ]) : '';
                },
                'delete' => function ($url, $model) {
                    return Yii::$app->user->identity->isAdmin() && (int) Yii::$app->formatter->asTimestamp('now') > $model->date_from
                        ? Html::a('<span class="glyphicon glyphicon-remove"></span>',
                            ['competition/delete', 'id' => $model->id], [
                                'id' => 'remove-attibute',
                                'class' => 'button-delete-attribute',
                                'title' => Yii::t('app', 'Delete'),
                            ]) : '';
                }
            ]
        ],
    ],
]); ?>

views/competition/partials/team_create.php
<?php

use kartik\widgets\DepDrop;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

?>

<?php
$form = ActiveForm::begin([
    'id' => 'create-form',
]); ?>

<?= $form->field($model, 'competition_id')->dropDownList(ArrayHelper::map($competitions, 'id', 'name'), ['id' => 'parent', 'prompt' => 'Select ...'])->label('Competition') ?>

<?= $form->field($model, 'team_id')->widget(DepDrop::classname(), [
    'type' => DepDrop::TYPE_SELECT2,
    'data' => [],
    'options' => ['id' => 'sub', 'placeholder' => 'Select ...'],
    'select2Options' => ['pluginOptions' => ['allowClear' => true]],
    'pluginOptions' => [
        'depends' => ['parent'],
        'url' => Url::to(['/competition/available-team']),
    ]
])->label('Team');
?>

<div class="col-md-12">
    <?= Html::submitButton($model->isNewRecord ? 'Add' : 'Update', ['class' => 'btn btn-primary', 'style' => ['width' => '100%'], 'name' => 'create-button']) ?>
</div>

<?php ActiveForm::end(); ?>

views/competition/partials/team_search.php
<?php

use yii\grid\GridView;
use yii\helpers\Html;
?>


<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        'name',
        [
            'label' => 'Teams',
            'format' => 'raw',
            'value' => function($model) {
                /** @var $model \app\models\Competition */
                return $model->teamHtml();
            },
        ],
        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{update} {delete}',
            'buttons' => [
                'update' => function ($url, $model) {
                    return Yii::$app->user->identity->isAdmin() && (int) Yii::$app->formatter->asTimestamp('now') > $model->date_from
                        ? Html::a('<span class="glyphicon glyphicon-pencil"> </span>',
                            ['competition/index', 'id' => $model->id], [
                                'class' => 'button-attribute-update',
                                'title' => Yii::t('app', 'Update'),
                            ]) : '';
                },
                'delete' => function ($url, $model) {
                    return Yii::$app->user->identity->isAdmin() && (int) Yii::$app->formatter->asTimestamp('now') > $model->date_from
                        ? Html::a('<span class="glyphicon glyphicon-remove"></span>',
                            ['competition/delete', 'id' => $model->id], [
                                'id' => 'remove-attibute',
                                'class' => 'button-delete-attribute',
                                'title' => Yii::t('app', 'Delete'),
                            ]) : '';
                }
            ]
        ],
    ],
]); ?>