models/CompetitionMatch.php
<?php

namespace app\models;

use Yii;
use yii\helpers\Html;

/**
 * This is the model class for table "{{%competition_match}}".
 *
 * @property integer $id
 * @property integer $competition_id
 * @property integer $competition_team_1_id
 * @property integer $competition_team_2_id
 * @property integer $team_1_result
 * @property integer $team_2_result
 * @property integer $date
 *
 * @property Competition $competition
 * @property CompetitionTeam $competitionTeam1
 * @property CompetitionTeam $competitionTeam2
 * @property CompetitionMatchResult[] $competitionMatchResults
 * @property CompetitionMatchPlayer[] $competitionMatchPlayers
 * @property CompetitionMatchPlayer[] $competitionMatchTeam1Players
 * @property CompetitionMatchPlayer[] $competitionMatchTeam2Players
 */
class CompetitionMatch extends \yii\db\ActiveRecord
{

    public $playersTeam1 = [];
    public $playersTeam2 = [];

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%competition_match}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['competition_id', 'competition_team_1_id', 'competition_team_2_id', 'playersTeam1', 'playersTeam2'], 'required'],
            [['competition_team_1_id', 'competition_team_2_id'], function ($attribute, $params, $validator) {
                if ($this->competition_team_1_id == $this->competition_team_2_id) {
                    $this->addError($attribute, 'Teams are the same.');
                }
            }],
            [['playersTeam1', 'playersTeam2'], function ($attribute, $params, $validator) {
                if (sizeof($this->$attribute) != 6) {
                    $this->addError($attribute, 'Team must have 6 players.');
                }
            }],
            [['competition_id', 'competition_team_1_id', 'competition_team_2_id', 'team_1_result', 'team_2_result', 'date'], 'integer'],
            [['competition_id'], 'exist', 'skipOnError' => true, 'targetClass' => Competition::className(), 'targetAttribute' => ['competition_id' => 'id']],
            [['competition_team_1_id'], 'exist', 'skipOnError' => true, 'targetClass' => CompetitionTeam::className(), 'targetAttribute' => ['competition_team_1_id' => 'id']],
            [['competition_team_2_id'], 'exist', 'skipOnError' => true, 'targetClass' => CompetitionTeam::className(), 'targetAttribute' => ['competition_team_2_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'competition_id' => Yii::t('app', 'Competition ID'),
            'competition_team_1_id' => Yii::t('app', 'Competition Team 1 ID'),
            'competition_team_2_id' => Yii::t('app', 'Competition Team 2 ID'),
            'team_1_result' => Yii::t('app', 'Team 1 Result'),
            'team_2_result' => Yii::t('app', 'Team 2 Result'),
            'date' => Yii::t('app', 'Date'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompetition()
    {
        return $this->hasOne(Competition::className(), ['id' => 'competition_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompetitionTeam1()
    {
        return $this->hasOne(CompetitionTeam::className(), ['id' => 'competition_team_1_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompetitionTeam2()
    {
        return $this->hasOne(CompetitionTeam::className(), ['id' => 'competition_team_2_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompetitionMatchPlayers()
    {
        return $this->hasMany(CompetitionMatchPlayer::className(), ['competition_match_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompetitionMatchTeam1Players()
    {
        return $this->hasMany(CompetitionMatchPlayer::className(), ['competition_match_id' => 'id'])->onCondition(['competition_team_id' => $this->competition_team_1_id]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompetitionMatchTeam2Players()
    {
        return $this->hasMany(CompetitionMatchPlayer::className(), ['competition_match_id' => 'id'])->onCondition(['competition_team_id' => $this->competition_team_2_id]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompetitionMatchResults()
    {
        return $this->hasMany(CompetitionMatchResult::className(), ['competition_match_id' => 'id']);
    }

    /**
     * @return bool|int
     */
    public function saveMatch()
    {
        if (!$this->save()) {
            return false;
        }

        $batchInsert = [];
        foreach ($this->playersTeam1 as $player) {
            $batchInsert[] = [
                $this->id,
                $this->competition_team_1_id,
                $player
            ];
        }

        foreach ($this->playersTeam2 as $player) {
            $batchInsert[] = [
                $this->id,
                $this->competition_team_2_id,
                $player
            ];
        }

        $result = Yii::$app->db->createCommand()->batchInsert(CompetitionMatchPlayer::tableName(), [
            'competition_match_id',
            'competition_team_id',
            'player_id'
        ], $batchInsert)->execute();

        return $result;
    }


    public function getTeamNames()
    {
        return $this->competitionTeam1->team->name . ' vs. ' . $this->competitionTeam2->team->name;
    }

    public function getTeam1Squad()
    {
        $html = '';
        foreach ($this->competitionMatchTeam1Players as $i) {
            $html .= Html::tag('li', $i->player->firstname . ' ' . $i->player->lastname);
        }

        return Html::tag('ul', $html);
    }

    public function getTeam2Squad()
    {
        $html = '';
        foreach ($this->competitionMatchTeam2Players as $i) {
            $html .= Html::tag('li', $i->player->firstname . ' ' . $i->player->lastname);
        }

        return Html::tag('ul', $html);
    }

    public function getResult()
    {
        $results = $this->competitionMatchResults;
        if ($results) {
            $html = '( ' . $this->team_1_result . ' : ' . $this->team_2_result . ' )';
            $html .= Html::tag('li', $results[0]->set1 . ' : ' . $results[1]->set1);
            $html .= Html::tag('li', $results[0]->set2 . ' : ' . $results[1]->set2);
            $html .= Html::tag('li', $results[0]->set3 . ' : ' . $results[1]->set3);
            if (isset($results[0]->set4) && isset($results[1]->set4)) {
                $html .= Html::tag('li', $results[0]->set4 . ' : ' . $results[1]->set4);
            }
            if (isset($results[0]->set5) && isset($results[1]->set5)) {
                $html .= Html::tag('li', $results[0]->set5 . ' : ' . $results[1]->set5);
            }
            return Html::tag('ul', $html);
        }
        return null;
    }

}

controllers/CompetitionMatchesController.php
<?php

namespace app\controllers;

use app\models\Competition;
use app\models\CompetitionMatch;
use app\models\CompetitionTeam;
use app\models\MatchResultForm;
use app\models\Player;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\web\Response;

class CompetitionMatchesController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'available-players', 'available-teams', 'update'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @param null $id
     * @return string
     */
    public function actionIndex($id = null)
    {
        if (!$id) {
            $model = new CompetitionMatch;
        } else {
            $model = CompetitionMatch::findOne($id);
        }

        if ($model && $model->load(Yii::$app->request->post()) && $model->saveMatch()) {
            Yii::$app->session->setFlash('success', 'Success.');
            $model = new CompetitionMatch();
        }

        $dataProvider = new ActiveDataProvider([
            'query' => CompetitionMatch::find(),
        ]);

        return $this->render('index', [
            'model' => $model,
            'dataProvider' => $dataProvider,
            'teams' => CompetitionTeam::find()->all(),
            'competitions' => Competition::find()->all(),
        ]);
    }


    /**
     * @return array
     */
    public function actionAvailablePlayers()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        if (Yii::$app->request->post()) {
            /** @var int $id Shop.id */
            $id = Yii::$app->request->getBodyParam('depdrop_parents');
            if (is_array($id)) {
                $id = $id[0];
            }
            $output = Player::forDepDrop($id);
            return ['output' => $output, 'selected' => ''];
        }
        return ['output' => '', 'selected' => ''];
    }


    /**
     * @return array
     */
    public function actionAvailableTeams()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        if (Yii::$app->request->post()) {
            /** @var int $id Shop.id */
            $id = Yii::$app->request->getBodyParam('depdrop_parents');
            if (is_array($id)) {
                $id = $id[0];
            }
            $out = CompetitionTeam::teamsForDepDrop($id);
            return ['output' => $out, 'selected' => ''];
        }
        return ['output' => '', 'selected' => ''];
    }

    /**
     * @param $id
     * @return string|Response
     */
    public function actionUpdate($id)
    {
        $match = CompetitionMatch::findOne($id);
        if ($match) {
            $model = new MatchResultForm(['match' => $match]);
            if ($model->load(Yii::$app->request->post()) && $model->saveResult()) {
                Yii::$app->session->setFlash('success', 'Success.');
            }
            return $this->render('result', ['match' => $match, 'model' => $model]);
        }

       return $this->redirect(['index']);
    }

}

views/competition-matches/partials/create.php
<?php

use kartik\widgets\DepDrop;
use yii\bootstrap\Html;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

?>

<?php
$form = ActiveForm::begin([
    'id' => 'create-form',
]); ?>

<div class="row">
    <div class="col-md-4">
        <?= $form->field($model, 'competition_id')->dropDownList(ArrayHelper::map($competitions, 'id', 'name'), ['id' => 'competition', 'prompt' => 'Select ...'])->label('Competition') ?>
    </div>
    <div class="col-md-4">
        <?= $form->field($model, 'competition_team_1_id')->widget(DepDrop::classname(), [
            'type' => DepDrop::TYPE_DEFAULT,
            'data' => [],
            'options' => ['id' => 'parent1', 'placeholder' => 'Select ...'],
            'select2Options' => ['pluginOptions' => ['allowClear' => true]],
            'pluginOptions' => [
                'depends' => ['competition'],
                'url' => Url::to(['/competition-matches/available-teams']),
            ]
        ])->label('Team 1'); ?>
    </div>
    <div class="col-md-4">
        <?= $form->field($model, 'competition_team_2_id')->widget(DepDrop::classname(), [
            'type' => DepDrop::TYPE_DEFAULT,
            'data' => [],
            'options' => ['id' => 'parent2', 'placeholder' => 'Select ...'],
            'select2Options' => ['pluginOptions' => ['allowClear' => true]],
            'pluginOptions' => [
                'depends' => ['competition'],
                'url' => Url::to(['/competition-matches/available-teams']),
            ]
        ])->label('Team 2'); ?>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <?= $form->field($model, 'playersTeam1')->widget(DepDrop::classname(), [
            'type' => DepDrop::TYPE_SELECT2,
            'data' => [],
            'options' => ['id' => 'sub1', 'placeholder' => 'Select ...', 'multiple' => true],
            'select2Options' => ['pluginOptions' => ['allowClear' => true]],
            'pluginOptions' => [
                'depends' => ['parent1'],
                'url' => Url::to(['/competition-matches/available-players']),
            ]
        ])->label('Squad 1'); ?>
    </div>
    <div class="col-md-6">
        <?= $form->field($model, 'playersTeam2')->widget(DepDrop::classname(), [
            'type' => DepDrop::TYPE_SELECT2,
            'data' => [],
            'options' => ['id' => 'sub2', 'placeholder' => 'Select ...' , 'multiple' => true],
            'select2Options' => ['pluginOptions' => ['allowClear' => true]],
            'pluginOptions' => [
                'depends' => ['parent2'],
                'url' => Url::to(['/competition-matches/available-players']),
            ]
        ])->label('Squad 2'); ?>
    </div>
</div>
<div class="col-md-12">
    <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => 'btn btn-primary', 'style' => ['width' => '100%'], 'name' => 'create-button']) ?>
</div>
<?php ActiveForm::end(); ?>

views/competition-matches/partials/search.php
<?php

use app\models\CompetitionMatch;
use yii\grid\GridView;
use yii\helpers\Html;


?>

<div style="margin-top: 20px">
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            [
                'label' => 'Competition',
                'attribute' => 'competition.name',
            ],
            [
                'label' => 'Teams',
                'value' => function ($model) {
                    /** @var $model CompetitionMatch */

                    return $model->getTeamNames();
                },
            ],
            [
                'label' => 'Squad Team 1',
                'format' => 'raw',
                'value' => function ($model) {
                    /** @var $model CompetitionMatch */

                    return $model->getTeam1Squad();
                },
            ],
            [
                'label' => 'Squad Team 2',
                'format' => 'raw',
                'value' => function ($model) {
                    /** @var $model CompetitionMatch */

                    return $model->getTeam2Squad();
                },
            ],
            [
                'label' => 'Result',
                'format' => 'raw',
                'value' => function ($model) {
                    /** @var $model CompetitionMatch */
                    return $model->getResult();
                },
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update}',
                'buttons' => [
                    'update' => function ($url, $model) {
                        /** @var $model CompetitionMatch */
                        return Yii::$app->user->identity->isAdmin() && !$model->competitionMatchResults
                            ? Html::a('<span class="glyphicon glyphicon-flag"> </span>',
                                ['competition-matches/update', 'id' => $model->id], [
                                    'class' => 'button-attribute-update',
                                    'title' => Yii::t('app', 'Result'),
                                ]) : '';
                    },
                ]
            ],
        ],
    ]); ?>


</div>